# Generated by Django 3.2.7 on 2023-10-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_like_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, unique=True)),
                ('hashtags', models.ManyToManyField(blank=True, to='movies.Movie')),
            ],
        ),
    ]
